services:
  diddht-a:
    build:
      context: impl
      dockerfile: build/Dockerfile
    environment:
      STORAGE_URI: postgres://postgres:aa@postgres/postgres
    depends_on:
      - postgres
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8305/health"]
      interval: 5s
      timeout: 1s
      retries: 10
  diddht-b:
    build:
      context: impl
      dockerfile: build/Dockerfile
    environment:
      STORAGE_URI: postgres://postgres:aa@postgres/postgres
    depends_on:
      - postgres
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8305/health"]
      interval: 5s
      timeout: 1s
      retries: 10
  postgres:
    image: library/postgres
    command: ["-E"]
    environment:
      POSTGRES_PASSWORD: aa
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
  concurrencytest:
    build:
      context: impl
      dockerfile_inline: |
        FROM library/golang:latest
        COPY . /go/diddht
        WORKDIR /go/diddht
        RUN go build -o /concurrencytest ./concurrencytest
    command: "/concurrencytest"
    depends_on:
      - diddht-a
      - diddht-b
