[server]
env = "dev"
api_host = "0.0.0.0"
api_port = 8305
listen_port = 8503
log_location = "log"
log_level = "debug"
db_file = "diddht.db"

[dht]
name = "tbd"
namespace = "diddht"
topic = "diddht"
local_discovery = false
resolver_endpoint = "https://dev.uniresolver.io/"
bootstrap_peers = ["/ip4/54.174.122.8/tcp/8503/p2p/12D3KooWR7KTAszwXmkfr5U18VrKvCgwDC3FHdrgMcrZBr3Z9Eig"]
enforce_signed_messages = false

[gossip]
enforce_signed_messages = false