[server]
env = "dev"
api_host = "0.0.0.0"
api_port = 8305
listen_port = 8503
log_location = "log"
log_level = "debug"
db_file = "diddht.db"

[dht]
name = "tbd"
namespace = "diddht"
topic = "diddht"
local_discovery = false
resolver_endpoint = "https://dev.uniresolver.io/"
bootstrap_peers = ["/ip4/54.226.19.143/tcp/8503/p2p/12D3KooWBKXjfe8H6Vd2o6vYiKc6PBqyphrVGgAF3ytN6VfPn6Ff"]
enforce_signed_messages = false