// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package postgres

type DhtRecord struct {
	ID    int32
	Key   []byte
	Value []byte
	Sig   []byte
	Seq   int64
}

type FailedRecord struct {
	ID           []byte
	FailureCount int32
}
