[server]
env = "dev"
api_host = "0.0.0.0"
api_port = 8305
log_location = "log"
log_level = "debug"
storage_uri = "bolt://diddht.db"

[dht]
bootstrap_peers = ["router.magnets.im:6881", "router.bittorrent.com:6881", "dht.transmissionbt.com:6881",
    "router.utorrent.com:6881", "router.nuh.dev:6881"]

[pkarr]
republish_cron = "0 */2 * * *" # every 2 hours
cache_ttl_seconds = 600 # 10 minutes
cache_size_limit_mb = 500 # 512 MB
