name: did-dht-ci

# when:
#   - a pull request is opened against main
#   - commits are pushed to main
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  # used to run action manually via the UI
  workflow_dispatch:

jobs:
  vulnerability-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.21.3

      - name: Install Mage
        working-directory: ./impl
        run: go install github.com/magefile/mage

      - name: Check Vulnerabilities
        working-directory: ./impl
        run: mage -v vuln
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.21.3

      - name: Install Mage
        working-directory: ./impl
        run: go install github.com/magefile/mage

      - name: Build
        working-directory: ./impl
        run: mage build

      - name: Test
        working-directory: ./impl
        run: mage citest